spring:
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
server:
  port: 9094
  servlet:
    context-path: /mystazyapp/api
  multipart:
    enabled: true
    max-file-size: 50MB
    max-request-size: 50MB
app:
  open-api:
    domain-endpoints: ${TEST_OPEN_API_DOMAIN}
  security:
    jwt:
      secret: ${TEST_JWT_SECRET}
      expiration-ms: ${TEST_JWT_EXPIRATION_MS}
      refresh-token-expiration-days: ${TEST_JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
    allowed-origins:
        -${TEST_ALLOWED_ORIGIN_1}
        -${TEST_ALLOWED_ORIGIN_2}
otp:
    expiration:
        minutes: ${TEST_OTP_EXPIRATION_MINUTES}
pg:
  photos:
    upload-dir: ${TEST_PG_PHOTOS_UPLOAD_DIR}
    url-base: http://localhost:9092${server.servlet.context-path}/photos/
tenant:
    photos:
        profile-dir: ${TEST_TENANT_PROFILE_PHOTO_DIR}
        id-proof-dir: ${TEST_TENANT_ID_PROOF_PHOTO_DIR}
booking:
  photos:
    id-proof-dir:${TEST_TENANT_ID_PROOF_PHOTO_DIR}
    profile-dir:${TEST_TENANT_PROFILE_PHOTO_DIR}
firebase:
    config:
      path: ${TEST_FIREBASE_SERVICE_ACCOUNT_FILE}